# customization - #default keeps everyone in the dataset and old_age subsets
# the data to 55+ years old

# specify WHICH_CONFIG="default" or WHICH_CONFIG="old_age" in the terminal

default: 
  whole_dataset: TRUE
  
old_age:
  whole_dataset: FALSE
