---
title: "Bingbing_Graph"
author: "Bingbing Wu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(tidyverse)
```

## Read in data
```{r}
here::i_am("code/Bingbing_graph.R")

data <- read.csv(
  file = here::here("raw_data/covid_sub.csv")
)
```

## Oraginize Data
```{r}
# Convert categorical columns to factors
data <- data %>%
  mutate_at(vars(USMER, 
                 SEX, 
                 PATIENT_TYPE, 
                 INTUBED, 
                 PNEUMONIA, 
                 PREGNANT, 
                 DIABETES, 
                 COPD, 
                 ASTHMA, 
                 INMSUPR, 
                 HIPERTENSION, 
                 OTHER_DISEASE, 
                 CARDIOVASCULAR, 
                 OBESITY, 
                 RENAL_CHRONIC, 
                 TOBACCO, 
                 ICU), 
            factor)
```

```{r}
# Handling missing values: For simplicity, we'll convert NAs in binary columns to "Unknown"
binary_columns <- c("INTUBED", 
                    "PNEUMONIA", 
                    "PREGNANT", 
                    "DIABETES", 
                    "COPD", 
                    "ASTHMA", 
                    "INMSUPR", 
                    "HIPERTENSION", 
                    "OTHER_DISEASE", 
                    "CARDIOVASCULAR", 
                    "OBESITY", 
                    "RENAL_CHRONIC", 
                    "TOBACCO", 
                    "ICU")

data[binary_columns] <- lapply(data[binary_columns], function(x) addNA(x, ifany = TRUE))
```

```{r}
# Assuming 'DATE_DIED' is NA for patients who didn't die, creating a binary outcome variable for mortality
data$DIED <- ifelse(is.na(data$DATE_DIED), "No", "Yes")
```

## Analysis
```{r}
# Create a subset of data focusing on patient outcomes and conditions
analysis_data <- data %>%
  select(SEX, AGE, PATIENT_TYPE, DIED, INTUBED, PNEUMONIA, DIABETES, COPD, ASTHMA, INMSUPR, HIPERTENSION, OTHER_DISEASE, CARDIOVASCULAR, OBESITY, RENAL_CHRONIC, TOBACCO, ICU)

```

###### Grouping age into categories
```{r}
analysis_data$AGE <- as.numeric(as.character(analysis_data$AGE))

analysis_data$AGE_GROUP <- cut(analysis_data$AGE, breaks = c(0, 18, 40, 60, 80, Inf), 
                               labels = c("0-18", 
                                          "19-40", 
                                          "41-60", 
                                          "61-80", 
                                          "81+"), 
                               right = FALSE)
```

##### Calculating mortality rate by age group and any pre-existing condition
```{r}
mortality_rate <- analysis_data %>%
  mutate(ANY_CONDITION = ifelse(DIABETES == "Yes" | COPD == "Yes" | ASTHMA == "Yes" | INMSUPR == "Yes" | HIPERTENSION == "Yes" | OTHER_DISEASE == "Yes" | CARDIOVASCULAR == "Yes" | OBESITY == "Yes" | RENAL_CHRONIC == "Yes" | TOBACCO == "Yes", "Yes", "No")) %>%
  group_by(AGE_GROUP, ANY_CONDITION) %>%
  summarise(Mortality_Rate = mean(DIED == "Yes"), .groups = 'drop')
```

## Creating a graph to analyze treatment outcomes and healthcare utilization
```{r}
# Plotting
bar_graph <- ggplot(mortality_rate, aes(x = AGE_GROUP, y = Mortality_Rate, fill = ANY_CONDITION)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "COVID-19 Mortality Rate by Age Group and Pre-existing Condition",
       x = "Age Group",
       y = "Mortality Rate",
       fill = "Pre-existing Condition")
```
```{r}
# Saving Graph
ggsave(
  here::here ("output/Bingbing_graph.png"),
  plot = bar_graph,
  device = "png"
)
```

